import os

# ==============================================================================
# 1. SETUP PATHS
# ==============================================================================
base_dir = "C:/Users/jgspe/Documents/Brazil_ENSO_Sugarcane"
output_file = os.path.join(base_dir, "Data_Dictionary.md")

# ==============================================================================
# 2. DEFINE THE ENHANCED MARKDOWN CONTENT
# ==============================================================================
markdown_content = """# Data Dictionary: Sugarcane ENSO Database (`Sugarcane_ENSO.db`)

## 1. Overview & Data Scope
This database harmonizes 56 growing seasons (1962–2018) of weather observations and DSSAT/CANEGRO sugarcane simulation outputs[cite: 5]. The system is designed to analyze yield anomalies driven by the El Niño-Southern Oscillation (ENSO) across three primary Brazilian regions (CENTRO, NORTE, SUL), with the architectural capacity to scale to 24 geographical locations[cite: 5, 13].

The schema is built in **Third Normal Form (3NF)** to eliminate redundancy[cite: 25]. Variable definitions and metadata are mapped to the **ICASA** (International Consortium for Agricultural Systems Applications) standards to ensure global interoperability[cite: 22].

---

## 2. Global Data Handling & Standards
To maintain logical consistency and academic reproducibility, the processing pipeline adheres to the following rules[cite: 8, 14]:

* **Missing Values:** Raw meteorological anomalies (e.g., `-99`, `-99.0`) and software-specific missing strings (e.g., `NA`) are programmatically converted to **SQL NULL** during ingestion[cite: 27].
* **Date Formats:** All dates are standardized to the **ISO 8601** format (`YYYY-MM-DD`)[cite: 23].
* **Hierarchy:** The project follows a strict hierarchical folder structure: `Data_Raw`, `Data_Processed`, `Scripts`, and `Visualizations` [cite: 16-21].

---

## 3. Table Schemas

### Table 1: `ENSO_Lookup`
**Description:** A dimension table storing the historical ENSO phase classification for each growing season.

| Column Name | Data Type | Key Type | ICASA Map | Description / Units |
| :--- | :--- | :--- | :--- | :--- |
| `Year` | INTEGER | Primary Key | `YEAR` | The harvest year (YYYY) of the simulation. |
| `Phase` | TEXT | None | N/A | ENSO classification: `EN` (El Niño), `LA` (La Niña), or `NE` (Neutral). |

---

### Table 2: `Locations`
**Description:** A dimension table defining the geographical regions where meteorological data was observed.

| Column Name | Data Type | Key Type | ICASA Map | Description / Units |
| :--- | :--- | :--- | :--- | :--- |
| `Loc_ID` | INTEGER | Primary Key | `WSTA` | Unique identifier for the region[cite: 23]. |
| `Station_Code` | TEXT | Unique | `WSTA_ID` | String code representing the region (e.g., `BR_CENTRO`). |
| `City_Name` | TEXT | None | N/A | Descriptive name of the geographical region. |
| `Latitude` | REAL | None | `FLAT` | Latitude coordinate (Decimal Degrees). |
| `Longitude` | REAL | None | `FLONG` | Longitude coordinate (Decimal Degrees). |

---

### Table 3: `Weather_Daily`
**Description:** A fact table containing daily historical meteorological observations sourced from INMET[cite: 6].

| Column Name | Data Type | Key Type | ICASA Map | Description / Units |
| :--- | :--- | :--- | :--- | :--- |
| `Weather_ID` | INTEGER | Primary Key | N/A | Auto-incremented unique identifier. |
| `Loc_ID` | INTEGER | Foreign Key | `WSTA` | Links to the `Locations` table. |
| `Date` | TEXT | None | `DATE` | Observation date (ISO 8601 format)[cite: 23]. |
| `TMAX` | REAL | None | `TMAX` | Maximum daily air temperature (°C). |
| `TMIN` | REAL | None | `TMIN` | Minimum daily air temperature (°C). |
| `PRCP` | REAL | None | `RAIN` | Total daily precipitation (mm). |
| `SRAD` | REAL | None | `SRAD` | Total daily solar radiation (MJ/m²/day). |

---

### Table 4: `Yield_Results`
**Description:** A fact table storing the agronomic outputs generated by the DSSAT/CANEGRO crop model[cite: 6].

| Column Name | Data Type | Key Type | ICASA Map | Description / Units |
| :--- | :--- | :--- | :--- | :--- |
| `Result_ID` | INTEGER | Primary Key | N/A | Auto-incremented unique identifier. |
| `Region` | TEXT | None | N/A | String identifying the simulation region. |
| `Year` | INTEGER | Foreign Key | `YEAR` | Harvest year, linking to `ENSO_Lookup`. |
| `Sowing_Date` | TEXT | None | `SDAT` | The date of sowing (ISO 8601 format)[cite: 23]. |
| `Harvest_Month` | TEXT | None | N/A | The designated month of harvest. |
| `TCH_t_ha` | REAL | None | `HWAM` | Tonnes of Cane per Hectare (Stalk Fresh Yield). *Scale x1000 for ICASA kg/ha equivalent*[cite: 23]. |
| `Sugar_Yield_kg_tc` | REAL | None | `SUCM` | Sucrose mass extracted per tonne of cane (kg/tc). |
| `TSH_t_ha` | REAL | None | `SUCM` | Tonnes of Sugar per Hectare (Total Recoverable Sugar). |

---

## 4. FAIR Principles Summary [cite: 33]
* **Findable:** Code and schemas are versioned via Git and hosted on GitHub with comprehensive documentation[cite: 31, 34].
* **Accessible:** The SQLite database is accessible via standard open-source tools like DB Browser for SQLite[cite: 35].
* **Interoperable:** Variable naming and metadata adhere to the ICASA global ontology for crop modeling[cite: 22, 36].
* **Reusable:** All processing scripts are heavily commented and released under the open-source MIT License[cite: 37].
"""

# ==============================================================================
# 3. WRITE THE FILE
# ==============================================================================
print(f"Generating Proposal-Compliant Data Dictionary at: {output_file}...")

try:
    with open(output_file, "w", encoding="utf-8") as file:
        file.write(markdown_content)
    print("Success! Data_Dictionary.md has been updated to meet project objectives.")
except Exception as e:
    print(f"An error occurred while writing the file: {e}")